---
title: "About"
---

We launched in [Spring 2023](https://princeton-r-group.github.io/events.html#spring-2023) as an initiative between graduate students Kim Kreiss (SPIA) and Angela Li (SOC). Since then, we have been co-organized by DDSS Graduate Fellows of Social Data Science and DDSS staff members.

We primarily focus on **applied use cases of R in research**, with a target audience of grad students and scholars who use the programming language in their work.

We aim to pick topics that are **widely applicable** across research areas, such as reproducible research, package development, and data visualization. Our event attendees have included researchers from all over the university.

**We welcome R users of all levels to our events.** However, because we focus on research use cases, our events tend to assume some working knowledge of R. Feel free to reach out to us if you have questions about an event.

Note that we do not currently provide introductory workshops in R as there are many resources around the university that provide excellent training (see below).

## Learning R?

For more resources at Princeton for getting started with R, please check out the [Exploring R page](https://exploringr.princeton.edu/).

> Thanks to the work of Sorat Tungkasiri (Digital Learning Lab), Alex Hollinghead (Digital Learning Lab), Oscar Torres-Reyna (Economics), and Carolina Roe-Raymond (Princeton Institute for Computational Science and Engineering and Research Computing) for this excellent resource!

We recommend the workshops and individual consulting through [Data and Statistical Services](https://library.princeton.edu/services/data-and-statistical-services), based in Stokes Library. A list of workshops offered across campus in Fall 2024 is below.

Additionally, check out the [Getting Started in Data Analysis in R](https://libguides.princeton.edu/dss/R) library guide compiled by Economics Librarian Bobray Bordelon.

## Events from campus partners

### Research Computing

-   [**Using R on the Research Computing Clusters**](https://my.princeton.edu/click?email_links_id=50959&member_id=14727542)

    -   Tuesday, October 8 at 3:00-4:30 PM
    -   Location: A15 Fine Hall (Fine Visualization Laboratory)
    -   Instructor: Galen Collier, Director of Researcher Engagement, Research Computing

-   [**Working with R tidyr and dplyr Packages**](https://libcal.princeton.edu/calendar/events/Rtidyversef2024)

    -   Wednesday, October 23, 2024 at 1:30-3:00 PM
    -   Location: Stokes Viz Hub - Donald E. Stokes Library, Room 070
    -   Instructor: Boriana Pratt, Statistical Programmer, Office of Population Research

### Stokes Viz Hub

-   [Intro to R for Social Sciences](https://libcal.princeton.edu/calendar/events/Rintroaf2024)

    -   Monday, October 21, 2024 at 3:00-4:30 PM
    -   Location: Stokes Viz Hub - Donald E. Stokes Library, Room 070
    -   Instructor: Ameet Doshi, Head Stokes Library

-   [Intro to R for Social Sciences](https://libcal.princeton.edu/calendar/events/Rintrobf2024)

    -   Monday, October 28, 2024 at 3:00-4:30 PM
    -   Location: Stokes Viz Hub - Donald E. Stokes Library, Room 070
    -   Instructor: Ameet Doshi, Head Stokes Library

-   [Data Visualization with R - Introduction to ggplot](https://libcal.princeton.edu/calendar/events/Rggplotf2024)

    -   November 6, 2024 at 1:30-3:00 PM
    -   Location: Stokes Viz Hub - Donald E. Stokes Library, Room 070
    -   Instructors: Ofira Schwartz, Social Sciences Data & Sociology Librarian

### Data and Statistical Services

-   [Introduction to Data Analysis with R](https://libcal.princeton.edu/event/12987209)

    -   Friday, September 27, 2024 at 10:30 AM-12:00 PM
    -   Location: Firestone Library - A-6-F

-   [Introduction to Data Analysis with R](https://libcal.princeton.edu/event/12987525)

    -   Friday, October 4, 2024 at 1:30-3:00 PM
    -   Location: Firestone Library - B-6-F

-   [Introduction to Data Analysis with R](https://libcal.princeton.edu/event/12987325)

    -   Friday, November 1, 2024 at 10:30 AM-12:00 PM
    -   Location: Firestone Library - A-6-F

## Current and past co-organizers

The Princeton tigeRs co-organizers for 2024-2025 are DDSS Graduate Fellow Angela Li and DDSS Research Data Engineer Eric Manning. We also thank [DDSS staff members](https://ddss.princeton.edu/staff-and-scholars) Karyn Gerecitano and Jess Hollinger for their support with events.

Our past co-organizers have been:

-   2023-2024: Kim Kreiss (DDSS Grad Fellow) and Angela Li (DDSS Grad Fellow)
